# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DatosPlusPlus',
                'doc_host': 'https://dci-courses.github.io',
                'git_url': 'https://github.com/dci-courses/DatosPlusPlus',
                'lib_path': 'DatosPlusPlus'},
  'syms': {'DatosPlusPlus.core': {'DatosPlusPlus.core.foo': ('core.html#foo', 'DatosPlusPlus/core.py')}}}
